darkcrusade: Improved
It contains the following changes:

- A better help text.

- Tarball names are now composed by "Year-number+Month-name+Day-number"
  for multiple passes or multiple executions of darkcrusade.

- Better handling in case of errors, the script now stops if an error occurs.

- Minor changes.

Thanks to the great Bob Proulx for all his suggestions.

Signed-off-by: Matías Fonzo <selk@dragora.org>

diff --git a/darkcrusade b/darkcrusade
--- a/darkcrusade
+++ b/darkcrusade
@@ -2,7 +2,7 @@
 #
 # Deploy static cross-compilers for easy distribution
 #
-# Copyright (c) 2016-2020 Matias Fonzo, <selk@dragora.org>.
+# Copyright (c) 2016-2021 Matias Fonzo, <selk@dragora.org>.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -16,19 +16,19 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-PROGRAM="${0##*/}"
-
 # Exit immediately on any error
 set -e
- 
+
+PROGRAM="${0##*/}"
+
 # Show help via option
 if test "$1" = -h || test "$1" = --help
 then
     echo "Usage: $PROGRAM [TARGET]..."
     echo "Deploy static cross-compilers for easy distribution."
     echo ""
-    echo "Where TARGET is any target found in the \"targets/\" directory."
-    echo "If no target names are passed, all available targets will be built."
+    echo "Where TARGET is any target found at the targets/ directory."
+    echo "If no target name is passed, all available targets will be built."
     echo ""
     exit 0;
 fi
@@ -36,6 +36,8 @@ fi
 # Override locale settings
 LC_ALL=C
 export LC_ALL
+
+umask 022
 
 ### Default values
 
@@ -46,15 +48,15 @@ CWD="$(CDPATH='' cd -P -- "$(dirname -- "$0")" && pwd -P)"
 output="${CWD}/OUTPUT.darkcrusade"
 
 # Set temporary directory for compilation, exporting it
-TMPDIR=${output}/sources
+TMPDIR="${output}"/sources
 export TMPDIR
 
-# Compose tag for tarball names using year+month+day
-tarname=darkcrusade_"$(date +%Y%b)"
+# Compose tag for tarball names using Year-number+Month-name+Day-number
+tarname="darkcrusade_$(date +%Y%b%d)"
 
 # Prepare to start the cross compiler process in the phase 1
 
-phase_one=${output}/phase1-native-"$(uname -m)".$$
+phase_one="${output}/phase1-native-$(uname -m)-$(date +%Y-%m-%d.%H:%M:%S).$$"
 
 echo "${PROGRAM}: Creating native cross compiler on $phase_one ..."
 "${CWD}"/bootstrap -s0 -o "$phase_one"
@@ -94,29 +96,37 @@ export BTCC BTCXX IS_DARKCRUSADE
 for target in ${CWD}/targets/${@:-*}
 do
     target="${target##*/}"
-    phase_two=${output}/phase2-${target}.$$
+    phase_two="${output}/phase2-${target}-$(date +%Y-%m-%d.%H:%M:%S).$$"
+
+    # Build target against native compiler, logging its output
 
     echo "darkcrusade: Making target $target ..."
-    "${CWD}"/bootstrap -s0 -a "$target" -o "$phase_two" 2>&1 | \
-     tee "${output}/${tarname}-${target}.log"
+    rm -f "${output}/bootstrapfailed"
 
-    # Provide log file, tarball plus checkum
+    {
+        "${CWD}"/bootstrap -s0 -a "$target" -o "$phase_two" || touch "${output}/bootstrapfailed"
+    } 2>&1 | tee "${output}/${tarname}-${target}.log"
+
+    if test -f "${output}/bootstrapfailed"
+    then
+        echo "${PROGRAM}: An error occurred while processing the target: $target" 1>&2
+        echo "  Please check the log file ${output}/${tarname}-${target}.log" 1>&2
+        exit 99;
+    fi
+
+    # Provide log file, tarball and checkum
 
     lzip -9 "${output}/${tarname}-${target}.log" &
-    rm -f "${output}/${tarname}-${target}.tar" \
-          "${output}/${tarname}-${target}.tar.lz"
 
-    cd "$phase_two"
-    ( umask 022 ; tarlz --solid -9 -cvf - -- cross/ ) \
-     > "${output}/${tarname}-${target}.tar.lz"
-
+    (
+        cd -- "$phase_two" && \
+        tarlz --solid -9 -cvf - -- cross/ \
+         > "${output}/${tarname}-${target}.tar.lz"
+    )
     (
         cd -- "$output" && \
         sha256sum "${tarname}-${target}.tar.lz" \
          > "${tarname}-${target}.tar.lz.sha256"
     )
-
-    # Back to the current working directory
-    cd -- "$CWD"
 done
 
