recipes: tde/tqca_tls: patch updated
Signed-off-by: Matías Fonzo <selk@dragora.org>

diff --git a/recipes/tde/tqca_tls/recipe b/recipes/tde/tqca_tls/recipe
--- a/recipes/tde/tqca_tls/recipe
+++ b/recipes/tde/tqca_tls/recipe
@@ -47,7 +47,7 @@ build()
 
     if test -z "$QTDIR"
     then
-        echo "WARNING: QTDIR variable is empty." 1>&2
+        echo "WARNING: Required QTDIR variable is empty." 1>&2
         exit 1;
     fi
 
@@ -55,7 +55,7 @@ build()
 
     cd "$srcdir"
 
-    patch -Np1 -i "${worktree}/patches/tqca_tls/qca-tls_libressl.patch"
+    patch -p1 < "${worktree}/patches/tqca_tls/qca-tls_libressl.patch"
 
     # Set sane permissions
     chmod -R u+w,go-w,a+rX-s .
