qi: Make is_readable() function more flatter
Thanks to DustDFG.

Signed-off-by: Matías Fonzo <selk@dragora.org>

diff --git a/qi/src/qi.in b/qi/src/qi.in
--- a/qi/src/qi.in
+++ b/qi/src/qi.in
@@ -107,17 +107,17 @@ warn()
 
 is_readable()
 {
-    if test -e "$1"
+    if test ! -e "$1"
     then
-        if ! test -r "$1"
-        then
-            echo "${PROGRAM}: cannot read ${1}: Permission denied" 1>&2
-            return 1
-        fi
-    else
         echo "${PROGRAM}: cannot access ${1}: No such file or directory" 1>&2
         return 1
     fi
+    if test ! -r "$1"
+    then
+        echo "${PROGRAM}: cannot read ${1}: Permission denied" 1>&2
+        return 1
+    fi
+    return 0
 }
 
 # Portable alternative to the file operator -nt (among shells)
