stages: 2/04-iso: Minor changes
Signed-off-by: Matías Fonzo <selk@dragora.org>

diff --git a/stages/2/04-iso b/stages/2/04-iso
--- a/stages/2/04-iso
+++ b/stages/2/04-iso
@@ -31,7 +31,7 @@ fi
 if ! type mkisofs > /dev/null
 then
     echo "" 1>&2
-    echo "\`mkisofs' is not found in your PATH." 1>&2
+    echo "    \`mkisofs' is not found in your PATH ..." 1>&2
     if type genisoimage > /dev/null
     then
         MKISOFS=genisoimage
@@ -43,7 +43,7 @@ then
         exit 2;
     fi
 fi
-echo "Using \`${MKISOFS}' as the command for \${MKISOFS} ..."
+echo "The \`${MKISOFS}' command will be used to generate the .iso"
 
 # This depends on the existence of the stage 1
 
