stages: 2/04-iso: improve message when mkisofs/genisoimage is not found

diff --git a/stages/2/04-iso b/stages/2/04-iso
--- a/stages/2/04-iso
+++ b/stages/2/04-iso
@@ -27,12 +27,16 @@ then
 fi
 if ! type mkisofs > /dev/null
 then
-    echo "mkisofs is not found in your PATH, trying to find genisoimage ..." 1>&2
+    echo "" 1>&2
+    echo "\`mkisofs' is not found in your PATH." 1>&2
     if type genisoimage > /dev/null
     then
         MKISOFS=genisoimage
     else
-        echo "mkisofs or genisoimage are not found in your PATH for proceed." 1>&2
+        echo "\`genisoimage' was not found in your PATH." 1>&2
+        echo "" 1>&2
+        echo "Please install one of these programs to make the ISO image." 1>&2
+        echo "" 1>&2
         exit 2;
     fi
 fi
