linux-libre upgraded to version 4.14.9

diff --git a/recipes/kernel/generic/recipe b/recipes/kernel/generic/recipe
--- a/recipes/kernel/generic/recipe
+++ b/recipes/kernel/generic/recipe
@@ -15,7 +15,7 @@
 # limitations under the License.
 
 program=linux
-version=4.14.8
+version=4.14.9
 release=1
 
 pkgname=kernel-generic
@@ -79,6 +79,9 @@ build()
         exit 1;
         ;;
     esac
+
+    echo "ABORTED for config"
+    exit 99
 
     make -j${jobs} bzImage
     make -j${jobs} modules
