recipes: kernel/generic: add flag to the recipe for config purposes

diff --git a/recipes/kernel/generic/recipe b/recipes/kernel/generic/recipe
--- a/recipes/kernel/generic/recipe
+++ b/recipes/kernel/generic/recipe
@@ -76,9 +76,12 @@ build()
         ;;
     esac
 
-    # Uncomment these lines for configuration purposes
-    echo "ABORTED for config"
-    exit 99
+    # An environment variable for config purposes
+    if test ! -z "$ABORT_FOR_CONFIG"
+    then
+        echo "ABORT_FOR_CONFIG has been set."
+        exit 99;
+    fi
 
     make -j${jobs} bzImage
     make -j${jobs} modules
