recipes: kernel/generic: commented lines for testing purposes, sorry

diff --git a/recipes/kernel/generic/recipe b/recipes/kernel/generic/recipe
--- a/recipes/kernel/generic/recipe
+++ b/recipes/kernel/generic/recipe
@@ -83,8 +83,8 @@ build()
     esac
 
     # Uncomment these lines for configuration purposes
-    echo "ABORTED for config"
-    exit 99
+    #echo "ABORTED for config"
+    #exit 99
 
     make -j${jobs} bzImage
     make -j${jobs} modules
