linux-libre upgraded to version 4.14.35
The kernel configuration has been updated to use the safe version of
Unicode that is used by the console for FAT file systems.  See:
http://www.kernel.org/doc/Documentation/filesystems/vfat.txt

The Digital Input Layer to produce "beeps" has been enabled (HD-AUDIO),
by default, it is in 'off'.

diff --git a/recipes/kernel/generic/recipe b/recipes/kernel/generic/recipe
--- a/recipes/kernel/generic/recipe
+++ b/recipes/kernel/generic/recipe
@@ -15,7 +15,7 @@
 # limitations under the License.
 
 program=linux
-version=4.14.32
+version=4.14.35
 release=1
 
 pkgname=kernel-generic
@@ -83,8 +83,8 @@ build()
     esac
 
     # Uncomment these lines for configuration purposes
-    #echo "ABORTED for config"
-    #exit 99
+    echo "ABORTED for config"
+    exit 99
 
     make -j${jobs} bzImage
     make -j${jobs} modules
