recipes: kernel/generic: comment lines for configuration purposes

diff --git a/recipes/kernel/generic/recipe b/recipes/kernel/generic/recipe
--- a/recipes/kernel/generic/recipe
+++ b/recipes/kernel/generic/recipe
@@ -80,8 +80,9 @@ build()
         ;;
     esac
 
-    echo "ABORTED for config"
-    exit 99
+    # Uncomment these lines for configuration purposes
+    #echo "ABORTED for config"
+    #exit 99
 
     make -j${jobs} bzImage
     make -j${jobs} modules
