linux-libre upgraded to the version 4.14.60

diff --git a/recipes/kernel/generic/recipe b/recipes/kernel/generic/recipe
--- a/recipes/kernel/generic/recipe
+++ b/recipes/kernel/generic/recipe
@@ -15,8 +15,8 @@
 # limitations under the License.
 
 program=linux
-version=4.14.56
-release=3
+version=4.14.60
+release=1
 
 # Set 'outdir' for a nice and well-organized output directory
 outdir="${outdir}/${arch}/kernel"
@@ -77,8 +77,8 @@ build()
     esac
 
     # Uncomment these lines for configuration purposes
-    #echo "ABORTED for config"
-    #exit 99
+    echo "ABORTED for config"
+    exit 99
 
     make -j${jobs} bzImage
     make -j${jobs} modules
