archive: dragora-installer/parts/MakeFS: enhanced to work properly

diff --git a/archive/dragora-installer/parts/MakeFS b/archive/dragora-installer/parts/MakeFS
--- a/archive/dragora-installer/parts/MakeFS
+++ b/archive/dragora-installer/parts/MakeFS
@@ -1,10 +1,10 @@
 # This file is part of the 'dragora-installer'.
 #
-# Purpose: Linux partition(s) and mount points.
+# Purpose: Set Linux partition(s) and mount points.
 
 # Add or refresh list of partitions taking initial
 # list of partitions and temporary fstab into account
-makelist()
+makeMenu()
 {
     while read -r line
     do
@@ -12,14 +12,14 @@ makelist()
 
         device="${line%% *}"				# Device name.
         size="$(echo $line | awk '{ print $5 }')"	# Size field.
-        mnt_point="$( echo "$(awk '{ print $2 }' ${SUBTMPDIR}/fstab 2> /dev/null)" )"
-        format_fs="$( echo "$(awk '{ print $3 }' ${SUBTMPDIR}/fstab 2> /dev/null)" )"
 
-        # Figure out specific file system if it is unknown
-        format_fs="${format_fs:=$(blkid -s TYPE -o value $device)}"
-        export format_fs;	# To propagate it over functions.
+        # Get device mount point and file system type
+        devpoint="$(awk -v patr=$device '$1 == patr { print $2 }' ${SUBTMPDIR}/fstab 2> /dev/null)"
+        formatfs="$(awk -v patr=$device '$1 == patr { print $3 }' ${SUBTMPDIR}/fstab 2> /dev/null)"
+        formatfs="${formatfs:-$(blkid -s TYPE -o value $device 2> /dev/null)}"
 
-        echo "\"${device}\" \"$format_fs [${size}] ${mnt_point}\" \\" \
+        # Write entry to be showed on the MakeFS menu
+        echo "\"${device}\" \"${formatfs:-Linux} ${size} $devpoint\" \\" \
          >> ${SUBTMPDIR}/MakeFS_menu
 
     done < ${SUBTMPDIR}/partitions
@@ -53,42 +53,45 @@ this blank, any previous entries will be deleted:" 19 63 \
     # blank spaces.  We are not managing the octal tab character
     # (011) since TAB is a functional key in dialog(1).
 
-    mnt_point="$(sed -e "s/[\'\"]//g" -e 's/[[:blank:]]/\\040/g' \
+    mntpoint="$(sed -e "s/[\'\"]//g" -e 's/[[:blank:]]/\\040/g' \
                   ${SUBTMPDIR}/return-MakeFS_askMountPoint)"
 
-    if test -n "$mnt_point"
+    if test -n "$mntpoint"
     then
         # Determine the sixth field for the fstab
-        case $mnt_point in
+        case $mntpoint in
         /)  fs_passno=1;;
         *)  fs_passno=2;;
         esac
 
-        # Figure out device UUID to be added in the fstab
-        devid="$(blkid $1 | cut -f 2 -d ' ')"
+        # Refresh file system type information
+        formatfs="$(blkid -s TYPE -o value $1 2> /dev/null)"
 
-        # Write entry to the fstab removing possible duplicates
+        # Write fstab entry
 
         printf "%-43s %-14s %-12s %-16s %-3s %s\n" \
-         "$devid" "$mnt_point" "$format_fs" "defaults" "1" "${fs_passno}" \
+         "$1" "$mntpoint" "$formatfs" "defaults" "1" "${fs_passno}" \
          >> ${SUBTMPDIR}/fstab
+
         unset fs_passno
 
-        if test "$(grep -c "^$devid" ${SUBTMPDIR}/fstab)" -gt 1
+        # Remove possible duplicates
+        if test "$(grep -c "^$1" ${SUBTMPDIR}/fstab)" -gt 1
         then
-            repeated="$(grep -m 1 -n "^$devid" ${SUBTMPDIR}/fstab)"
+            repeated="$(grep -m 1 -n "^$1" ${SUBTMPDIR}/fstab)"
             repeated="${repeated%%:*}"
             sed -i "${repeated}d" ${SUBTMPDIR}/fstab
             unset repeated
         fi
-        unset mnt_point
-    else # Remove the whole entry
-        if test -n "$devid"
+    else # Remove the whole fstab entry
+        if test -n "$1"
         then
-            sed -i "/^${devid}/d" ${SUBTMPDIR}/fstab
-            unset devid
+            escape_slash="$(echo $1 | sed 's/\//\\\//g')"
+            sed -i "/${escape_slash}/d" ${SUBTMPDIR}/fstab
+            unset escape_slash
         fi
     fi
+    unset mntpoint
 }
 
 _mkfs()
@@ -190,33 +193,33 @@ dialog --colors \\
  --menu \\
 "The following Linux partitions has been detected:\n\n\\
   Selecting a partition gives you the possibility to set up\n\\
-a file system or a mount point for the boot stage of the system.  \\
-Once this has been established, choose the \\"Done\\" button to \
+a file system or a mount point for the boot stage of the system. \\
+Once this has been established, choose the \\"Done\\" button to \\
 continue with the installation." 16 65 5 \\
 EOF
-    makelist; . ${SUBTMPDIR}/MakeFS_menu
-    case ${_code:-$?} in
+    makeMenu && . ${SUBTMPDIR}/MakeFS_menu
+    case "${_code:-$?}" in
     0)
-        device="$(cat -- ${SUBTMPDIR}/return-MakeFS_menu)"
+        PARTITION="$(cat -- ${SUBTMPDIR}/return-MakeFS_menu)"
 
-        if test -z "$device"
+        if test -z "$PARTITION"
         then
-            echo "${PROGRAM}: Error the device list is empty." 1>&2
+            echo "${PROGRAM}: Error the partition list is empty." 1>&2
             exit 99;
         fi
 
-        if test -n "$format_fs"
+        if test -n "$(blkid -s TYPE -o value $PARTITION 2> /dev/null)"
         then
             dialog --colors \
              --backtitle "\ZbPartitions and mount points" \
-             --title "$device" \
+             --title "$PARTITION" \
              --no-cancel --menu \
-"* Selected device already contains a file system [${format_fs}] *\n\n\
+"* Selected device already contains a file system [${formatfs}] *\n\n\
 You can assign a mount point for system startup, you also\n\
 have the ability to re-format the partition.  If you choose\n\
 the latter, you will lose all your data and will be asked\n\
 for a mounting point.\n\n\
-What would you like to do for '${device}'?" 17 64 3 \
+What would you like to do for '${PARTITION}'?" 17 64 3 \
              "0" "Assign a mount point" \
              "1" "Format again (data loss risk)" \
              "<" "Return to previous menu" \
@@ -224,11 +227,11 @@ What would you like to do for '${device}'?" 17 64 3 \
 
             # Check for selected options
             case "$(cat -- ${SUBTMPDIR}/return-MakeFS_menu_case)" in
-            0)  askMountPoint $device ;;
-            1)  formatMenu $device && askMountPoint $device ;;
+            0)  askMountPoint $PARTITION;;
+            1)  formatMenu $PARTITION && askMountPoint $PARTITION;;
             esac
         else
-            formatMenu $device && askMountPoint $device
+            formatMenu $PARTITION && askMountPoint $PARTITION
         fi
         ;;
     3)
@@ -243,8 +246,8 @@ What would you like to do for '${device}'?" 17 64 3 \
              --ok-label "Return" --msgbox \
 "There is no declared mount point for the root partition.\n\n\
   Please go back and assign a mount point for the\n\
-root partition.  Remember that the mount point must be\n\
-declared as \"/\" (without quotes and spaces)." 10 60 || \
+root partition.  Remember that the mount point must\n\
+be declared as \"/\" (without quotes and spaces)." 10 60 || \
              { unset _code ; continue ; }
         fi
         ;;
@@ -255,6 +258,5 @@ declared as \"/\" (without quotes and spaces)." 10 60 || \
     unset _code;	# To take the value again.
 done
 
-unset _code device format_fs _status \
-      makelist askMountPoint _mkfs formatMenu
+unset makeMenu _mkfs _mkxfs FormatMenu formatfs _code _status
 
