qi: Bump to version 1.5 (Release Candidate 1)
Signed-off-by: Matías Fonzo <selk@dragora.org>

diff --git a/qi/configure b/qi/configure
--- a/qi/configure
+++ b/qi/configure
@@ -2,7 +2,7 @@
 #
 # Simple `configure' script for Qi.
 #
-# Copyright (c) 2016-2018 Matias Fonzo, <selk@dragora.org>.
+# Copyright (c) 2016-2018, 2020 Matias Fonzo, <selk@dragora.org>.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -187,12 +187,10 @@ done
 
 echo "Creating config.mak ..."
 
-# Show variales and clean up the config.mak file
+return_variables;		# Show configured variables.
+: > config.mak;			# Clean up config.mak, first.
 
-return_variables; : > config.mak
-
-# To populate config.mak
-return_variables > config.mak
-
-echo "OK, now you can run \`make'"
+return_variables > config.mak && \
+ echo "OK, now you can run \`make'"
+exit $?
 
