archive: dragora-installer/parts: added swap maker

diff --git a/archive/dragora-installer/dragora-installer b/archive/dragora-installer/dragora-installer
--- a/archive/dragora-installer/dragora-installer
+++ b/archive/dragora-installer/dragora-installer
@@ -135,6 +135,9 @@ will be displayed." 7 63
     fi
 fi
 
+# Clean up possible empty mount-directory
+rmdir -- /media/dragora-mount 2> /dev/null || true
+
 # Double-check to see the installation directory
 if test ! -f "${SUBTMPDIR}/MediumFound"
 then
@@ -149,6 +152,5 @@ packages." 8 55
     exit 99;
 fi
 
-# Clean up possible empty mount-directory
-rmdir -- /media/dragora-mount 2> /dev/null || true
+. ./parts/MakeSwap	# Verify/give format to a swap partition.
 
