archive: dragora-installer: added new part to mount the root partition

diff --git a/archive/dragora-installer/dragora-installer b/archive/dragora-installer/dragora-installer
--- a/archive/dragora-installer/dragora-installer
+++ b/archive/dragora-installer/dragora-installer
@@ -138,8 +138,10 @@ will be displayed." 7 63
     fi
 fi
 
-# Clean up possible empty mount-directory
-rmdir -- /media/dragora-medium 2> /dev/null || true
+# Clean up possible empty mount-directories
+rmdir -- \
+ /media/dragora-medium \
+ /media/dragora-root 2> /dev/null || true
 
 # Double-check to see the installation directory
 if test ! -f "${SUBTMPDIR}/MediumFound"
@@ -158,4 +160,5 @@ fi
 . ./parts/MakeSwap	# Verify/give format to a Swap partition.
 . ./parts/MakeFS	# Verify/give format to Linux partitions.
 . ./parts/FstabEdit	# File system table edition (fstab).
+. ./parts/MountRoot	# Mount root partition for installation.
 
